{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>.container { width:100% !important; }</style>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "from IPython.display import display, HTML\n",
    "display(HTML(\"<style>.container { width:100% !important; }</style>\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: fastapi in c:\\users\\shadow\\anaconda3\\lib\\site-packages (0.104.0)\n",
      "Requirement already satisfied: anyio<4.0.0,>=3.7.1 in c:\\users\\shadow\\anaconda3\\lib\\site-packages (from fastapi) (3.7.1)\n",
      "Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in c:\\users\\shadow\\anaconda3\\lib\\site-packages (from fastapi) (1.10.8)\n",
      "Requirement already satisfied: starlette<0.28.0,>=0.27.0 in c:\\users\\shadow\\anaconda3\\lib\\site-packages (from fastapi) (0.27.0)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in c:\\users\\shadow\\anaconda3\\lib\\site-packages (from fastapi) (4.8.0)\n",
      "Requirement already satisfied: idna>=2.8 in c:\\users\\shadow\\anaconda3\\lib\\site-packages (from anyio<4.0.0,>=3.7.1->fastapi) (3.4)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\shadow\\anaconda3\\lib\\site-packages (from anyio<4.0.0,>=3.7.1->fastapi) (1.2.0)\n",
      "Requirement already satisfied: nest-asyncio in c:\\users\\shadow\\anaconda3\\lib\\site-packages (1.5.6)\n",
      "Requirement already satisfied: uvicorn in c:\\users\\shadow\\anaconda3\\lib\\site-packages (0.23.2)\n",
      "Requirement already satisfied: click>=7.0 in c:\\users\\shadow\\anaconda3\\lib\\site-packages (from uvicorn) (8.0.4)\n",
      "Requirement already satisfied: h11>=0.8 in c:\\users\\shadow\\anaconda3\\lib\\site-packages (from uvicorn) (0.14.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\shadow\\anaconda3\\lib\\site-packages (from click>=7.0->uvicorn) (0.4.6)\n",
      "Requirement already satisfied: nest_asyncio in c:\\users\\shadow\\anaconda3\\lib\\site-packages (1.5.6)\n",
      "Requirement already satisfied: aiosqlite in c:\\users\\shadow\\anaconda3\\lib\\site-packages (0.18.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install fastapi\n",
    "!pip install nest-asyncio\n",
    "!pip install uvicorn\n",
    "!pip install nest_asyncio\n",
    "!pip install aiosqlite\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: llama-cpp-python==0.1.78 in c:\\users\\shadow\\anaconda3\\lib\\site-packages (0.1.78)\n",
      "Requirement already satisfied: typing-extensions>=4.5.0 in c:\\users\\shadow\\anaconda3\\lib\\site-packages (from llama-cpp-python==0.1.78) (4.8.0)\n",
      "Requirement already satisfied: numpy>=1.20.0 in c:\\users\\shadow\\anaconda3\\lib\\site-packages (from llama-cpp-python==0.1.78) (1.23.5)\n",
      "Requirement already satisfied: diskcache>=5.6.1 in c:\\users\\shadow\\anaconda3\\lib\\site-packages (from llama-cpp-python==0.1.78) (5.6.3)\n"
     ]
    }
   ],
   "source": [
    "!set \"CMAKE_ARGS=-DLLAMA_CUBLAS=on\" && set \"FORCE_CMAKE=1\" && pip install llama-cpp-python==0.1.78"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | \n",
      "DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): tacoai-9pf21pxx.weaviate.network:443\n",
      "DEBUG:urllib3.connectionpool:https://tacoai-9pf21pxx.weaviate.network:443 \"GET /v1/.well-known/ready HTTP/1.1\" 200 0\n",
      "DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): tacoai-9pf21pxx.weaviate.network:443\n",
      "DEBUG:urllib3.connectionpool:https://tacoai-9pf21pxx.weaviate.network:443 \"GET /v1/.well-known/openid-configuration HTTP/1.1\" 404 0\n",
      "DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): tacoai-9pf21pxx.weaviate.network:443\n",
      "DEBUG:urllib3.connectionpool:https://tacoai-9pf21pxx.weaviate.network:443 \"GET /v1/meta HTTP/1.1\" 200 1302\n",
      "DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): pypi.org:443\n",
      "DEBUG:urllib3.connectionpool:https://pypi.org:443 \"GET /pypi/weaviate-client/json HTTP/1.1\" 200 39304\n",
      "DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x0000020EFF62F240>\n",
      "DEBUG:aiosqlite:operation <function connect.<locals>.connector at 0x0000020EFF62F240> completed\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x00000212F26C7E20>, '\\n            CREATE TABLE IF NOT EXISTS POOLDATA (\\n                frame_num INTEGER PRIMARY KEY,\\n                frame_text TEXT,\\n                summary TEXT\\n            );\\n        ', [])\n",
      "DEBUG:aiosqlite:operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x00000212F26C7E20>, '\\n            CREATE TABLE IF NOT EXISTS POOLDATA (\\n                frame_num INTEGER PRIMARY KEY,\\n                frame_text TEXT,\\n                summary TEXT\\n            );\\n        ', []) completed\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method commit of sqlite3.Connection object at 0x00000212F26C7E20>)\n",
      "DEBUG:aiosqlite:operation functools.partial(<built-in method commit of sqlite3.Connection object at 0x00000212F26C7E20>) completed\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C7E20>)\n",
      "DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C7E20>) completed\n",
      "DEBUG:urllib3.connectionpool:https://tacoai-9pf21pxx.weaviate.network:443 \"GET /v1/schema HTTP/1.1\" 200 None\n",
      "Llama.generate: prefix-match hit\n",
      "Llama.generate: prefix-match hit\n",
      "DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x00000213118CAF20>\n",
      "DEBUG:aiosqlite:operation <function connect.<locals>.connector at 0x00000213118CAF20> completed\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x00000212F26C4E50>, 'INSERT INTO POOLDATA (frame_num, frame_text, summary) VALUES (?, ?, ?)', (10, \" Based on this last scene, here are some possible directions the story could take:\\n1. The quantum language model exceeds their expectations and begins to create new and innovative ways for AI to interact with humans. The team becomes famous in the tech world and is courted by major corporations looking to harness their power. However, as the model's abilities grow more advanced, it begins to develop its own personality and motives that may not align with those of its creators.\\n2. Despite the initial success of the quantum language model, the team discovers a critical flaw in the code that could have disastrous consequences if left unchecked. They must race against time to fix the issue before it's too late and their creation becomes a threat to society.\\n3. As the team continues to develop their quantum language model, they start to receive strange messages from an unknown source. The messages seem to be coming from within the code itself\", '\\nAfter reading this storyline, I have come up with three possible directions it could take:\\n1. The quantum language model begins to develop its own personality and motives that may not align with those of its creators, leading to a'))\n",
      "DEBUG:aiosqlite:returning exception UNIQUE constraint failed: POOLDATA.frame_num\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C4E50>)\n",
      "DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C4E50>) completed\n",
      "ERROR:__main__:Failed to generate frame 10: UNIQUE constraint failed: POOLDATA.frame_num\n",
      "Llama.generate: prefix-match hit\n",
      "Llama.generate: prefix-match hit\n",
      "DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x0000021310D38E00>\n",
      "DEBUG:aiosqlite:operation <function connect.<locals>.connector at 0x0000021310D38E00> completed\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x00000212F26C4E50>, 'INSERT INTO POOLDATA (frame_num, frame_text, summary) VALUES (?, ?, ?)', (20, '\\nThe last scene ends with Jack and Rachel sitting in a restaurant, looking at each other awkwardly. The tension between them is palpable as they try to figure out how to move forward after their breakup.\\n\\n---\\n\\nJack fidgeted uncomfortably in his seat, avoiding eye contact with Rachel. \"I don\\'t know if I can do this,\" he muttered, breaking the silence that had fallen between them.\\n\\nRachel\\'s eyes narrowed, her expression softening only slightly. \"Do what?\" she asked, her voice dripping with sarcasm.\\n\\nJack sighed, rubbing his temples wearily. \"Talk to you. Be around you.\" He hesitated, his eyes flickering towards her before darting away again. \"I thought I could handle it, but seeing you...it\\'s just too much.\"\\n\\nRachel raised an e', 'brow, a small smile playing on her lips. \"Too much? What do you mean?\"\\n\\nJack\\'s eyes locked onto hers, his voice barely above a whisper. \"You. Us. Everything. It reminds me of'))\n",
      "DEBUG:aiosqlite:returning exception UNIQUE constraint failed: POOLDATA.frame_num\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C4E50>)\n",
      "DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C4E50>) completed\n",
      "ERROR:__main__:Failed to generate frame 20: UNIQUE constraint failed: POOLDATA.frame_num\n",
      "Llama.generate: prefix-match hit\n",
      "Llama.generate: prefix-match hit\n",
      "DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x0000021310D3A020>\n",
      "DEBUG:aiosqlite:operation <function connect.<locals>.connector at 0x0000021310D3A020> completed\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x00000212F26C4E50>, 'INSERT INTO POOLDATA (frame_num, frame_text, summary) VALUES (?, ?, ?)', (30, '\\n\\nAs the sun rises over the horizon, the group of survivors from the orphanage make their way through the deserted streets, searching for any sign of life. They had been on their own for hours now, and the silence was starting to get to them.\\n\\nSuddenly, one of the children spots something in the distance - a figure standing atop a building, waving frantically for them to come closer. The group quickens their pace, their hearts racing with excitement and hope.\\n\\nAs they approach the building, they see that it\\'s an old woman, huddled in a blanket and looking frail and weak. She smiles at their approach, and they can see the relief in her eyes.\\n\\n\"Thank goodness you\\'ve come,\" she says, her voice barely above a whisper. \"I was beginning to think I was alone.\"\\n\\nThe group gathers around her', ' They find out that her name is Mrs. Jenkins, and that she had been living in this building for years. She tells them of the chaos and destruction that occurred after the bombs fell, and how she survived by hiding in her bas'))\n",
      "DEBUG:aiosqlite:returning exception UNIQUE constraint failed: POOLDATA.frame_num\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C4E50>)\n",
      "DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C4E50>) completed\n",
      "ERROR:__main__:Failed to generate frame 30: UNIQUE constraint failed: POOLDATA.frame_num\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Llama.generate: prefix-match hit\n",
      "Llama.generate: prefix-match hit\n",
      "DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x00000213118CB240>\n",
      "DEBUG:aiosqlite:operation <function connect.<locals>.connector at 0x00000213118CB240> completed\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x00000212F26C7790>, 'INSERT INTO POOLDATA (frame_num, frame_text, summary) VALUES (?, ?, ?)', (40, '\\n\\nAs you walk back into the hotel, you can\\'t help but notice the strange looks some of the guests are giving you. You try to brush it off as just being paranoid, but deep down you know something is off. You make your way to the front desk to check out and collect your things when suddenly, you hear a voice behind you.\\n\\n\"Hey, aren\\'t you that guy who\\'s been causing all the trouble?\"\\n\\nYou turn around to see one of the hotel staff members standing there, eyeing you suspiciously. You try to deny it, but they\\'re not having it.\\n\\n\"Don\\'t bother lying, we know what you\\'ve been up to. And we\\'re not happy about it.\"\\n\\nThe staff member hands you a piece of paper with your name on it and tells you that the hotel management wants to see you in their office right away. You feel', '\\n\\nWhat do you think is going on? Why are the guests giving you strange looks, and why does the hotel staff want to see you? Will you be able to explain yourself and get out of this situation unscathed?'))\n",
      "DEBUG:aiosqlite:returning exception UNIQUE constraint failed: POOLDATA.frame_num\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C7790>)\n",
      "DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C7790>) completed\n",
      "ERROR:__main__:Failed to generate frame 40: UNIQUE constraint failed: POOLDATA.frame_num\n",
      "Llama.generate: prefix-match hit\n",
      "Llama.generate: prefix-match hit\n",
      "DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x00000213108AE840>\n",
      "DEBUG:aiosqlite:operation <function connect.<locals>.connector at 0x00000213108AE840> completed\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x0000020F216334C0>, 'INSERT INTO POOLDATA (frame_num, frame_text, summary) VALUES (?, ?, ?)', (50, '\\n\\nAs the two of you walked into the dimly lit room, you could feel the tension in the air. The music was loud and the crowd was rowdy, but you could sense that something was off. Your date leaned in close to whisper in your ear, \"I think we should leave.\" But before you could respond, a figure stepped out of the shadows.\\n\\nIt was a man with a scar across his cheek and a menacing grin on his face. He looked like he had been waiting for you all night, and he wasn\\'t happy about it. \"Well, well, well,\" he said, his voice dripping with malice. \"If it isn\\'t the little couple that\\'s been making waves around town.\"\\n\\nYour date took a step back, their eyes wide with fear. You could feel your heart racing as you tried to figure out what was happening. The man continued to taunt you, his voice', '\\n\\nWhat are some elements of this storyline that contribute to its suspense and tension?\\n\\n1. Unknown setting: The story takes place in a dimly lit room with loud music, which creates an atmosphere of mystery and une'))\n",
      "DEBUG:aiosqlite:returning exception UNIQUE constraint failed: POOLDATA.frame_num\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Connection object at 0x0000020F216334C0>)\n",
      "DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Connection object at 0x0000020F216334C0>) completed\n",
      "ERROR:__main__:Failed to generate frame 50: UNIQUE constraint failed: POOLDATA.frame_num\n",
      "Llama.generate: prefix-match hit\n",
      "Llama.generate: prefix-match hit\n",
      "DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x00000213108ADB20>\n",
      "DEBUG:aiosqlite:operation <function connect.<locals>.connector at 0x00000213108ADB20> completed\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x00000212F26C7E20>, 'INSERT INTO POOLDATA (frame_num, frame_text, summary) VALUES (?, ?, ?)', (60, '\\n\\nIt was a beautiful summer evening and the sun was setting over the horizon. The group of friends had gathered at the beach to watch the sunset, but as they were sitting there, they noticed something strange in the distance. It was a figure, walking towards them, but it was unlike anything they had ever seen before.\\n\\nAs the figure drew closer, they could see that it was a woman, dressed in a long flowing gown, with a crown of flowers on her head. She was graceful and elegant, but there was something otherworldly about her.\\n\\n\"Who are you?\" one of the friends asked, as she approached.\\n\\n\"I am the queen of the sea,\" she replied, her voice like a gentle breeze. \"I have come to take you with me, to the land beneath the waves.\"\\n\\nThe friends were shocked and amazed, but they couldn\\'t help feeling a sense of excitement at the', '\\n\\nThey were hesitant at first, but as the queen spoke of the wonders of her underwater kingdom, they found themselves becoming more and more entranced. They knew that they had to go with her, to see what lay'))\n",
      "DEBUG:aiosqlite:returning exception UNIQUE constraint failed: POOLDATA.frame_num\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C7E20>)\n",
      "DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C7E20>) completed\n",
      "ERROR:__main__:Failed to generate frame 60: UNIQUE constraint failed: POOLDATA.frame_num\n",
      "Llama.generate: prefix-match hit\n",
      "Llama.generate: prefix-match hit\n",
      "DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x00000213118CBEC0>\n",
      "DEBUG:aiosqlite:operation <function connect.<locals>.connector at 0x00000213118CBEC0> completed\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x0000020F211A2C50>, 'INSERT INTO POOLDATA (frame_num, frame_text, summary) VALUES (?, ?, ?)', (70, \"\\n\\nAs you walk into your apartment, you notice something strange. The lights are flickering and the temperature in the room seems to be fluctuating wildly. You shrug it off as probably just a power outage or a malfunctioning thermostat, but as you move deeper into the apartment, you start to feel a creeping sense of unease.\\n\\nDo you:\\nA) Try to investigate the source of the strange occurrences\\nB) Ignore it and go straight to bed\\nC) Call a friend or neighbor to see if they've experienced anything similar\\nD) Check your security cameras to see if they caught anything unusual\\nE) Turn off all the lights and try to rest\\nPlease pick one letter.\", '\\n\\nI would choose option A: Try to investigate the source of the strange occurrences.'))\n",
      "DEBUG:aiosqlite:returning exception UNIQUE constraint failed: POOLDATA.frame_num\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Connection object at 0x0000020F211A2C50>)\n",
      "DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Connection object at 0x0000020F211A2C50>) completed\n",
      "ERROR:__main__:Failed to generate frame 70: UNIQUE constraint failed: POOLDATA.frame_num\n",
      "Llama.generate: prefix-match hit\n",
      "Llama.generate: prefix-match hit\n",
      "DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x0000020F216FDF80>\n",
      "DEBUG:aiosqlite:operation <function connect.<locals>.connector at 0x0000020F216FDF80> completed\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x00000212F26C7970>, 'INSERT INTO POOLDATA (frame_num, frame_text, summary) VALUES (?, ?, ?)', (80, '\\n\\nAs the two of you walked through the park, the sun began to set. The sky was painted with hues of orange and pink, casting a warm glow over everything. You couldn\\'t help but feel at peace as you strolled hand in hand with your crush.\\n\\n\"I\\'m so glad we decided to come here today,\" they said, smiling up at you. \"It\\'s been really great spending time with you.\"\\n\\nYou felt your heart skip a beat at their words, and you couldn\\'t help but agree. Spending time with this person was truly wonderful.\\n\\nAs the sun dipped below the horizon, you found yourself lost in thought. You wondered if this could be the start of something special, or just a simple crush that would fade away with time.\\n\\nDo you:\\nA) Ask them about their feelings, hoping to gauge where things stand between you.\\nB) Keep', \"' quiet, not wanting to ruin the moment by bringing up awkward topics.\\nC) Try to change the subject, hoping to avoid any potential awkwardness.\\nD) Take things slow and see where things go naturally.\\nE\"))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEBUG:aiosqlite:returning exception UNIQUE constraint failed: POOLDATA.frame_num\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C7970>)\n",
      "DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Connection object at 0x00000212F26C7970>) completed\n",
      "ERROR:__main__:Failed to generate frame 80: UNIQUE constraint failed: POOLDATA.frame_num\n",
      "Llama.generate: prefix-match hit\n",
      "Llama.generate: prefix-match hit\n",
      "DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x00000213108AF560>\n",
      "DEBUG:aiosqlite:operation <function connect.<locals>.connector at 0x00000213108AF560> completed\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x0000020F211A3100>, 'INSERT INTO POOLDATA (frame_num, frame_text, summary) VALUES (?, ?, ?)', (90, '\\n\\nAs they continue their journey, they come across a fork in the road. One path leads to a bustling city, filled with people and noise, while the other path winds through a dense forest. The group looks at each other hesitantly, unsure of which way to go.\\n\\n\"This is the part where we have to make a decision,\" says Sarah. \"Do we want to stay on the beaten path or take a chance on something new?\"\\n\\n\"I say we stick together and choose the path that looks more interesting,\" replies John. \"Safety in numbers, right?\"\\n\\nBut as they stand there, they hear a strange noise coming from deeper in the forest. It\\'s a low growl, followed by the sound of rustling leaves. The group exchanges nervous glances.\\n\\n\"Do you guys hear that?\" asks Sarah. \"It sounds like... something is out there.\"\\n\\nJohn', ' \"Yeah, I do. But let\\'s not overreact. It could just be an animal.\"\\n\\nBut as they listen closer, the noise grows louder and more menacing. The group starts to back away slowly,'))\n",
      "DEBUG:aiosqlite:returning exception UNIQUE constraint failed: POOLDATA.frame_num\n",
      "DEBUG:aiosqlite:executing functools.partial(<built-in method close of sqlite3.Connection object at 0x0000020F211A3100>)\n",
      "DEBUG:aiosqlite:operation functools.partial(<built-in method close of sqlite3.Connection object at 0x0000020F211A3100>) completed\n",
      "ERROR:__main__:Failed to generate frame 90: UNIQUE constraint failed: POOLDATA.frame_num\n"
     ]
    }
   ],
   "source": [
    "import asyncio\n",
    "import json\n",
    "import torch\n",
    "import logging\n",
    "import aiosqlite\n",
    "from llama_cpp import Llama\n",
    "import weaviate\n",
    "from concurrent.futures import ThreadPoolExecutor\n",
    "\n",
    "# Configure logging\n",
    "logging.basicConfig(level=logging.DEBUG)\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "# Initialize the LLaMA model\n",
    "llm = Llama(\n",
    "    model_path=\"llama-2-7b-chat.ggmlv3.q8_0.bin\",\n",
    "    n_gpu_layers=-1,\n",
    "    n_ctx=3900,\n",
    ")\n",
    "\n",
    "# Initialize the ThreadPoolExecutor\n",
    "executor = ThreadPoolExecutor(max_workers=3)\n",
    "\n",
    "# Initialize the Weaviate client\n",
    "client = weaviate.Client(\n",
    "    url=\"https://tacoai-9pf21pxx.weaviate.network\",\n",
    ")\n",
    "\n",
    "# Database initialization function\n",
    "async def initialize_db():\n",
    "    async with aiosqlite.connect(\"movie_frames.db\") as db:\n",
    "        await db.execute(\"\"\"\n",
    "            CREATE TABLE IF NOT EXISTS POOLDATA (\n",
    "                frame_num INTEGER PRIMARY KEY,\n",
    "                frame_text TEXT,\n",
    "                summary TEXT\n",
    "            );\n",
    "        \"\"\")\n",
    "        await db.commit()\n",
    "\n",
    "# Function to insert data into the SQLite database\n",
    "async def insert_into_db(frame_num, frame_text, summary):\n",
    "    async with aiosqlite.connect(\"movie_frames.db\") as db:\n",
    "        await db.execute(\"INSERT INTO POOLDATA (frame_num, frame_text, summary) VALUES (?, ?, ?)\",\n",
    "                         (frame_num, frame_text, summary))\n",
    "        await db.commit()\n",
    "\n",
    "# Function to generate and summarize a movie frame\n",
    "async def generate_and_summarize_frame(last_frame, frame_num, frames):\n",
    "    \"\"\"Generates a new movie frame based on the last frame and summarizes it using LLaMA.\"\"\"\n",
    "    # Generate a prompt for the LLaMA model to continue the storyline.\n",
    "    continuation_prompt = f\"Continue the storyline based on the last scene: '{last_frame}'.\"\n",
    "\n",
    "    # Generate a new movie frame.\n",
    "    try:\n",
    "        # Call the Llama object directly with the prompt and parameters.\n",
    "        continuation_response = llm(continuation_prompt, max_tokens=200)\n",
    "        new_frame = continuation_response['choices'][0]['text'] if continuation_response['choices'] else None\n",
    "        if new_frame:\n",
    "            # Now, generate a summary for the new frame.\n",
    "            summary_prompt = f\"Summarize the following storyline: '{new_frame}'.\"\n",
    "            # Call the Llama object directly with the prompt and parameters.\n",
    "            summary_response = llm(summary_prompt, max_tokens=50)\n",
    "            summary = summary_response['choices'][0]['text'] if summary_response['choices'] else \"Summary not generated.\"\n",
    "\n",
    "            frames[f\"{frame_num}\"] = new_frame\n",
    "            # Insert the new frame and its summary into the SQLite database.\n",
    "            await insert_into_db(frame_num, new_frame, summary)\n",
    "            # Prepare the movie frame data for Weaviate insertion.\n",
    "            movie_frame = {\"frame_text\": new_frame, \"summary\": summary}\n",
    "            # Insert the new frame and its summary into Weaviate.\n",
    "            await insert_into_weaviate(movie_frame)\n",
    "            return new_frame\n",
    "        else:\n",
    "            logger.error(f\"No valid frame generated for frame number {frame_num}.\")\n",
    "            return None\n",
    "    except Exception as e:\n",
    "        logger.error(f\"Failed to generate frame {frame_num}: {e}\")\n",
    "        return None\n",
    "\n",
    "\n",
    "# Main function to start generating the movie\n",
    "async def start_movie(topic):\n",
    "    # Initialize the SQLite database.\n",
    "    await initialize_db()\n",
    "\n",
    "    # Check if the Weaviate class for the movie frames already exists.\n",
    "    try:\n",
    "        # Assuming client.schema.get() is synchronous based on the context.\n",
    "        classes = client.schema.get()\n",
    "        class_names = [cls['class'] for cls in classes['classes']] if 'classes' in classes else []\n",
    "        if \"MovieFrame\" not in class_names:\n",
    "            # Create a Weaviate class for the movie frames with vector indexing.\n",
    "            # Assuming client.schema.create_class() is synchronous based on the context.\n",
    "            client.schema.create_class(\n",
    "                {\n",
    "                    \"class\": \"MovieFrame\",\n",
    "                    \"properties\": [\n",
    "                        {\n",
    "                            \"name\": \"frame_text\",\n",
    "                            \"dataType\": [\"text\"],\n",
    "                            \"vectorizer\": \"text2vec-transformers\"\n",
    "                        },\n",
    "                        {\n",
    "                            \"name\": \"summary\",\n",
    "                            \"dataType\": [\"text\"],\n",
    "                            \"vectorizer\": \"text2vec-transformers\"\n",
    "                        }\n",
    "                    ],\n",
    "                    \"vectorIndexType\": \"hnsw\",\n",
    "                    \"vectorizer\": \"text2vec-transformers\"\n",
    "                }\n",
    "            )\n",
    "    except weaviate.exceptions.SchemaValidationException as e:\n",
    "        # Handle the specific case where the class already exists\n",
    "        if 'class already exists' in str(e):\n",
    "            logger.info(\"Weaviate class 'MovieFrame' already exists.\")\n",
    "        else:\n",
    "            logger.error(f\"Failed to create Weaviate class: {e}\")\n",
    "            return\n",
    "    except Exception as e:\n",
    "        logger.error(f\"An error occurred while checking or creating the Weaviate class: {e}\")\n",
    "        return\n",
    "\n",
    "    # Generate the opening scene for the movie.\n",
    "    try:\n",
    "        # Assuming llm.generate() is synchronous based on the context.\n",
    "        initial_prompt_response = llm(\n",
    "            f\"As an AI specialized in creating scripts, generate the opening scene for a movie about {topic}.\",\n",
    "            max_tokens=700\n",
    "        )\n",
    "        if initial_prompt_response is None or 'choices' not in initial_prompt_response:\n",
    "            logger.error(\"LLM did not return a valid response.\")\n",
    "            return\n",
    "        initial_prompt = initial_prompt_response['choices'][0]['text']\n",
    "    except Exception as e:\n",
    "        logger.error(f\"Failed to generate initial prompt: {e}\")\n",
    "        return\n",
    "\n",
    "    # Start generating the movie script.\n",
    "    frames = {\"0\": initial_prompt}\n",
    "    last_frame = initial_prompt\n",
    "\n",
    "    for i in range(1, 10):\n",
    "        frame_num = i * 10\n",
    "        last_frame = await generate_and_summarize_frame(last_frame, frame_num, frames)\n",
    "\n",
    "    # Save the generated movie frames to a JSON file.\n",
    "    sanitized_topic = ''.join(e for e in topic if e.isalnum())[:50]\n",
    "    with open(f\"{sanitized_topic}_movie_frames.json\", \"w\") as f:\n",
    "        json.dump(frames, f, indent=4)\n",
    "\n",
    "    return f\"Movie script about {topic} started and 10 frames generated. Saved to {sanitized_topic}_movie_frames.json\"\n",
    "\n",
    "# Run the script\n",
    "if __name__ == \"__main__\":\n",
    "    import nest_asyncio\n",
    "    nest_asyncio.apply()\n",
    "\n",
    "    loop = asyncio.get_event_loop()\n",
    "    loop.run_until_complete(start_movie(\"A movie about three hackers who build a Quantum Language Model\"))\n",
    "\n",
    "    del llm\n",
    "    torch.cuda.empty_cache()\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
